# Generated by Django 4.2.5 on 2023-09-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity_on_stock',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.PositiveIntegerField(default=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchase',
            name='quantity_purchased',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
